Copy testing functions to main functions

diff --git a/commands/delete_pod b/commands/delete_pod
--- a/commands/delete_pod
+++ b/commands/delete_pod
@@ -1,12 +1,11 @@
 #!/bin/bash
 
-# delete_pod.sh name
+# delete_pod $pod_name
 
 user=""
 run=""
-
+logfile='/var/log/kube.log'
 TMPDIR="/tmp"
-
 
 while getopts "u:d" flag; do
 	case "$flag" in
@@ -28,84 +27,107 @@ while getopts "u:d" flag; do
 done
 
 pod_name=${@:$OPTIND:1}
-ssh_service_name="$pod_name-ssh"
 
 DIR="$(dirname "$(readlink -f "$0")")"
 
+get_pod_data() {
+    $DIR/get_containers_testing ${user:+"$user"} 2>&1 | grep "^$pod_name|"
+}
+readarray -d '|' -t podInfo < <(get_pod_data)
+
 # If user is given, check that user owns pod
 if [ -n "$user" ]; then
-	owner=`$DIR/get_containers 2>&1 | grep "^$pod_name|" | awk -F'|' '{print $6}'`
+	owner="${podInfo[5]}"
 	if [[ "$owner" != "" && "$owner" != "$user" ]]; then
-		echo "ERROR: pod $pod_name owned by $owner, NOT $user" >&2
+		  echo "ERROR: pod $pod_name owned by $owner, NOT $user" | tee -a "$logfile" >&2
 		exit 1
 	fi
 fi
 
-# First find the IP of the pod
-ip=`$DIR/get_containers 2>&1 | grep -E "^$pod_name\|" | awk -F'|' '{print $4}' | tr -d '\n'`
+stop_reverse_proxy() {
+    ip="${podInfo[3]}"
+    if [[ -n "$ip" ]]; then
+	      pid=`ps auxw | grep -E "caddy run .*\-\-config ${TMPDIR}/Caddyfile-${ip}-.*"  | grep -v grep | awk '{print $2}'`
+	      if [[ -n $pid ]]; then
+		        $run kill "$pid"
+		        rm "$TMPDIR/Caddyfile-${ip}-"* >& /dev/null
+		        rm "$TMPDIR/uri-${pod_name}"  >& /dev/null
+            echo "INFO: Stopped caddy proxy $TMPDIR/Caddyfile-${ip}-..." >> "$logfile"
+	      fi
+    fi
+}
 
-# Kill reverse proxy
-if [ -n "$ip" ]; then
-	pid=`ps auxw | grep -E "caddy run .*\-\-config ${TMPDIR}/Caddyfile-${ip}-.*"  | grep -v grep | awk '{print $2}'`
-	if [[ -n $pid ]]; then
-		$run kill "$pid"
-		rm "$TMPDIR/Caddyfile-${ip}-"* >& /dev/null
-		rm "$TMPDIR/uri-${pod_name}"  >& /dev/null
-	fi
-fi
+stop_ssh_service() {
+    ssh_service_name="${pod_name}-ssh"
+    $run kubectl get service "$ssh_service_name" >& /dev/null
+    if [[ "$?" == 0 ]]; then
+        echo "INFO: Stopping ssh loadbalance service $ssh_service_name" >> "$logfile"
+        $run kubectl delete service "$ssh_service_name" &>> "$logfile"
+        rm "$TMPDIR/hostkeys-${pod_name}"
+    fi
+}
 
-$run kubectl delete service "$ssh_service_name"
+check_claim_used() {
+    mount_regex='Mounted By:.*'
+    done_regex='[a-zA-Z]+:.*'
+    mount_start=""
+    mount_done=""
+    # Parse `kubectl describe pvc` because information about which pods use the claim is not available in the API object json
+    # Create array of all pods that use the persistent volume claim
+    while read line; do
+        if [[ -n $mount_start && -z $mount_done ]]; then
+            if [[ $line =~ $done_regex ]]; then
+                mount_done="true"
+            else
+                pods_with_claim[${#pods_with_claim[@]}]=$line
+            fi
+        else
+            if [[ -z $mount_start && $line =~ $mount_regex ]]; then
+                mount_start="true"
+                pods_with_claim[0]=$(sed -E 's/Mounted By:\s*//' <<< "$line")
+            fi
+        fi
+    done < <(kubectl describe pvc "$1")
+    if [[ ${#pods_with_claim[@]} -gt 1 ]]; then
+        echo "INFO: claim $1 used by more than one pod" >> "$logfile"
+        echo "true"
+    elif [[ "${pods_with_claim[0]}" != "$pod_name" && -n "${pods_with_claim[0]}" ]]; then
+        echo "INFO: claim $1 used by other pod ${pods_with_claim[0]}" >> "$logfile"
+        echo "true"
+    else
+        echo "false"
+    fi
+}
 
-### Clean up storage claims, volumes
+remove_claim_and_volume() {
+    #each volume can only be bound to one claim, so this should be safe
+		volume_name=$(kubectl get persistentvolumeclaim "$claim_name" -o json | jq -r ".spec.volumeName")
+    echo "INFO: deleting PVC $claim_name and PV $volume_name" >> "$logfile"
+    $run kubectl delete pvc "$claim_name" &>> "$logfile"
+    $run kubectl delete pv "$volume_name" &>> "$logfile"
+}
+
+remove_persistent_volumes() {
+    echo "$claims" |\
+        while read claim_name; do
+            if [[ $claim_name != "null" && -n $claim_name ]]; then
+                used_by_others=$(check_claim_used "$claim_name")
+                if [[ "$used_by_others" != "true" ]]; then
+                    remove_claim_and_volume "$claim_name"
+                fi
+            fi
+        done
+}
 
 # Find claims of this pod
-claims="`kubectl get pod "$pod_name" -o json | jq -r '.spec.volumes[] | select((.name == "sciencedata") or .name == "local") | .persistentVolumeClaim.claimName'`"
+claims="$(kubectl get pod "$pod_name" -o json | jq -r '.spec.volumes[] | select((.name == "sciencedata") or .name == "local") | .persistentVolumeClaim.claimName')"
 
 # Now we can delete the pod
-$run kubectl delete pod "$pod_name"
+echo "INFO: Deleting pod $pod_name" >> "$logfile"
+$run kubectl delete pod "$pod_name" &>> "$logfile" &
 
-# Check claims and delete if not used
-echo "$claims" |\
-while read claim_name; do
-	if [ $claim_name ]; then
-		# Check if other pods are using the claim
-		while read line; do
-			name=`echo $line | awk '{print $1}'`
-			if ! [ $name ]; then
-				continue
-			fi
-			claim=`kubectl get pod "$name" -o json | jq -r '.spec.volumes[] | select((.name == "sciencedata") or .name == "local") | .persistentVolumeClaim.claimName'`
-			if [ "$claim" == "$claim_name" ]; then
-				echo "Claim used by other pod $name" >&2
-				claim_active="yes"
-				break
-			fi
-		done < <( kubectl get pods 2>/dev/null | grep -Ev '^NAME ' | awk '{print $1}' | grep -Ev "^$pod_name$" )
-	fi
-
-	if [ $claim_name ] && [ -z $claim_active ]; then
-		# Find volume name
-		volume_name=`kubectl get persistentvolumeclaim "$claim_name" -o json | jq -r ".spec.volumeName"`
-		$run kubectl delete persistentvolumeclaim "$claim_name"
-		# Check if volume is used by other claims
-		while read line; do
-			name=`echo $line | awk '{print $1}'`
-			if ! [ $name ]; then
-				continue
-			fi
-			volume=`echo $line | awk '{print $3}'`
-			if [ "$volume" == "$volume_name" ]; then
-				echo "Volume used by other claim, $volume == $volume_name" >&2
-				volume_active="yes"
-				break
-			fi
-		done < <( kubectl get persistentvolumeclaims 2>/dev/null | grep -Ev '^NAME '  | awk '{print $1}' | grep -Ev "^$claim_name$" )
-	fi
-
-	if ! [ $claim_active ] && ! [ $volume_active ] && [ $volume_name ]; then
-		$run kubectl delete persistentvolume "$volume_name"
-	fi
-
-done
-
-
+# start slow processes and exit
+remove_persistent_volumes >& /dev/null &
+stop_reverse_proxy >& /dev/null &
+stop_ssh_service >& /dev/null &
+exit 0
diff --git a/commands/run_pod b/commands/run_pod
--- a/commands/run_pod
+++ b/commands/run_pod
@@ -6,6 +6,7 @@
 # run_pod -o fror@dtu.dk  -k "`cat ~/.ssh/id_rsa.pub`" -r www /root/sciencedata_kubernetes/pod_manifests/ubuntu_sciencedata.yaml
 # run_pod -o fror@dtu.dk -l /usr/local/software -p 8888 /root/sciencedata_kubernetes/pod_manifests/jupyter_sciencedata.yaml
 
+logfile='/var/log/kube.log'
 # If you have more than one public IP, you may need to hardcode EXTERNAL_IP
 EXTERNAL_IP=`hostname -I | sed "s| |\n|g" |  grep -E -v '^(192\.168|10\.|172\.1[6789]\.|172\.2[0-9]\.|172\.3[01]\.)' | head -1`
 # This presumes you've made an entry for sciencedata in /etc/hosts -if not, just hardcode SCIENCEDATA_IP
@@ -31,6 +32,49 @@ owner=""
 ssh_public_key=""
 nfs_storage_path=""
 dryrun=
+
+#### Define slow functions to run in background after successful pod creation
+start_reverse_proxy() {
+    # Wait for one minute for pod to start
+    for i in {1..6}; do
+        # Find local IP
+        pod_ip=$(kubectl get pod "$pod_name" -o json | jq -r '.status.podIP' | sed 's|null||')
+        if [[ -n "$pod_ip" ]]; then
+            echo "INFO: Running reverse proxy caddy reverse-proxy --from https://kube.sciencedata.dk:$reverse_proxy_port --to ${pod_ip}:${pod_http_port}" >> "$logfile"
+            caddyfile="$TMPDIR/Caddyfile-${pod_ip}-${reverse_proxy_port}-${pod_name}"
+            sed "s|WEBPORT|$reverse_proxy_port|" "$CADDY_FILE" > "$caddyfile"
+            sed -i "s|PODIP|$pod_ip|" "$caddyfile"
+            sed -i "s|PODPORT|$pod_http_port|" "$caddyfile"
+            export PATH=/bin/:/usr/bin:/usr/local/bin
+            caddy start -config "$caddyfile" &>> "/var/log/caddy/runpodproxy.log" &
+            kubectl exec --stdin ${pod_name} -- cat /tmp/URI 2>/dev/null > ${TMPDIR}/uri-${pod_name}
+            break
+        fi
+        sleep 10
+    done
+    if [[ -z "$pod_ip" ]]; then
+        echo "ERROR: pod $pod_name did not start. NOT running reverse proxy caddy reverse-proxy --from https://kube.sciencedata.dk:$reverse_proxy_port --to ${pod_ip}:${pod_http_port}." >> "$logfile"
+        exit 1
+    else
+        # Now wait in the background for another 5 minutes for any /tmp/URI to pop up in the container
+        ( for i in {1..60}; do
+              # If there's a file /tmp/URI, copy it out to /var/run/sciencedata/uri-${pod_name}
+              sleep 5
+              kubectl exec --stdin ${pod_name} -- cat /tmp/URI 2>/dev/null > ${TMPDIR}/uri-${pod_name}
+              [[ -e ${TMPDIR}/uri-${pod_name} ]] && [[ ! -s ${TMPDIR}/uri-${pod_name} ]] && rm ${TMPDIR}/uri-${pod_name}
+              [[ -s ${TMPDIR}/uri-${pod_name} ]] && break
+          done ) >& /dev/null
+    fi
+}
+copy_hostkeys() {
+    hostkey_file="${TMPDIR}/hostkeys-${pod_name}"
+    ( for i in {1..60}; do
+          sleep 5
+			    kubectl exec --stdin ${pod_name} -- cat /tmp/hostkeys 2>/dev/null > "$hostkey_file"
+			    [[ -e $hostkey_file ]] && [[ ! -s $hostkey_file ]] && rm $hostkey_file
+			    [[ -s $hostkey_file ]] && break
+      done ) >& /dev/null
+}
 
 while getopts "o:s:k:r:l:p:d" flag; do
 	case "$flag" in
@@ -128,7 +172,7 @@ if [ -z "$ssh_public_key" ]; then
 		# Try getting ssh public key from yaml
 		ssh_public_key="`cat \"$yaml_file\" | yq -r '.spec.containers[]?.env[]? | select(.name == \"SSH_PUBLIC_KEY\") | .value'`"
 		if [ -z "$ssh_public_key" ]; then
-			echo "WARNING: No SSH public key - it will not be possible to log in" >&2
+			echo "WARNING: No SSH public key - it will not be possible to log in" >> "$logfile"
 		fi
 	fi
 fi
@@ -150,7 +194,7 @@ if [ -z "$pod_http_port" ]; then
 		pod_http_port="`cat \"$yaml_file\" | yq -r '.spec.containers[]?.env[]? | select(.name == \"POD_HTTP_PORT\") | .value'`"
 		# If port 80 is exposed, we assume it's a web server
 		if [ -z "$pod_http_port" ]; then
-			pod_http_port="`cat \"$yaml_file\" | yq -r '.spec.containers[]?.ports[]? | select(.containerPort == 80 and .protocol == \"TCP\")' | .containerPort`"
+			pod_http_port="`cat \"$yaml_file\" | yq -r '.spec.containers[]?.ports[]? | select(.containerPort == 80 and .protocol == \"TCP\") | .containerPort'`"
 		fi
 	fi
 fi
@@ -178,24 +222,29 @@ fi
 
 # Check if home_server is set, otherwise check if $owner has a home server configured, finally to $SCIENCEDATA_IP
 if [ -z $home_server ]; then
-	home_server=`curl --insecure "https://${SCIENCEDATA_IP}/apps/files_sharding/ws/get_user_server.php?user_id=${owner}&internal=yes" | sed 's|\\/|/|g' | jq -r '.url' | grep -E 'https*://' | sed -E 's|^https*://||'`
+	home_server=`curl --insecure "https://${SCIENCEDATA_IP}/apps/files_sharding/ws/get_user_server.php?user_id=${owner}&internal=yes" | sed 's|\\/|/|g' | jq -r '.url' | grep -E 'https*://' | sed -E 's|^https*://||' 2> /dev/null`
 fi
-	
+
 if [ -n "$nfs_storage_path" ]; then
 	if [ -z $home_server ]; then
 		home_server=$SCIENCEDATA_IP
 	fi
 	# Check if directory exists
 	dir_exists_http_code=`curl --insecure -H "Depth: 0" -X PROPFIND -o /dev/null -w "%{http_code}" \
-	-u ${owner}: "https://${home_server}/storage/${nfs_storage_path}/"`
+	-u ${owner}: "https://${home_server}/storage/${nfs_storage_path}/" 2> /dev/null`
 	# Create if not
 	if [ "$dir_exists_http_code" != "207" ] && [ -z "$dryrun" ]; then
-		echo INFO: "https://${home_server}/storage/${nfs_storage_path}/ does NOT exist" >&2
-		curl --insecure -X MKCOL -u ${owner}: "https://${home_server}/storage/${nfs_storage_path}/"
+		echo "INFO: https://${home_server}/storage/${nfs_storage_path}/ does NOT exist" >> "$logfile"
+		dir_create_http_code=$(curl --insecure -X MKCOL -o /dev/null -w "%{http_code}" -u ${owner}: \
+                                "https://${home_server}/storage/${nfs_storage_path}/" 2> /dev/null)
+    if [[ $dir_create_http_code != 201 ]]; then
+      echo "WARNING: Failed to create storage directory" >> "$logfile"
+    fi
 	fi
+  nfs_volume_name="nfs-${home_server}-${owner_str}-$(sed 's|/|-|g' <<< "${nfs_storage_path}")"
 	if [ $home_server ]; then
 		# Check if the volume is already mounted
-		kubectl get persistentvolume | grep "^nfs-${home_server}-${owner_str}-${nfs_storage_path} " >& /dev/null
+		kubectl get persistentvolume | grep "^${nfs_volume_name} " >& /dev/null
 		if [ "$?" -ne "0" ]; then
 			create_nfs_volume="yes"
 		else
@@ -205,7 +254,7 @@ if [ -n "$nfs_storage_path" ]; then
 			fi
 		fi
 		# Check if a claim has already been made on $nfs_storage_path
-		kubectl get PersistentVolumeClaim | grep  "^nfs-${home_server}-${owner_str}-${nfs_storage_path} " >& /dev/null
+		kubectl get PersistentVolumeClaim | grep  "^${nfs_volume_name} " >& /dev/null
 		if [ "$?" -ne "0" ]; then
 			create_nfs_claim="yes"
 		fi
@@ -228,20 +277,27 @@ if [ -n "$local_storage_path" ]; then
 	fi
 fi
 
-# Find free port for Caddy proxy in range 2000-3000
-for reverse_proxy_port in {2000..3000}; do
-	ps aux | grep "caddy run .*\-\-config ${TMPDIR}/Caddyfile-.*-" >& /dev/null || break
-	ps auxw | grep caddy | grep -v "/etc/caddy/Caddyfile" | grep -v grep | grep -E "caddy run .*\-\-config ${TMPDIR}/Caddyfile-.*-${reverse_proxy_port}" >&/dev/null || break
-done
+# Find free port for Caddy proxy in range 2000-3000 iff there is a port to forward to
+if [[ -n $pod_http_port ]]; then
+  for reverse_proxy_port in {2000..3000}; do
+  	ps aux | grep "caddy run .*\-\-config ${TMPDIR}/Caddyfile-.*-" >& /dev/null || break
+  	ps auxw | grep caddy | grep -v "/etc/caddy/Caddyfile" | grep -v grep | grep -E "caddy run .*\-\-config ${TMPDIR}/Caddyfile-.*-${reverse_proxy_port}" >&/dev/null || break
+  done
+else
+  reverse_proxy_port=''
+fi
 
 # This is picked up by start.sh inside the container (for ScienceData-enabled containers)
 if [ $home_server ]; then
 	export my_home_server=`echo $home_server | sed "s|^$SCIENCEDATA_INTERNAL_NET|$SCIENCEDATA_PRIVATE_NET|"`
 fi
 
+cat $yaml_file > /tmp/joshualogs/baseyaml.yaml
+cat $yaml_file |\
+	  yq -r "(.spec.containers[]?.env[]? | select(.name == \"SSH_PUBLIC_KEY\") | .value) |= \"$ssh_public_key\"" > /tmp/joshualogs/onemod.yaml
 if [ -n "$pod_name" ]; then
 	### Modify pod YAML - ssh public key, metadata, volume. Pass the env variable FILE on.
-	( cat $yaml_file | \
+  modified_yaml=$( cat $yaml_file | \
 	yq -r "(.spec.containers[]?.env[]? | select(.name == \"SSH_PUBLIC_KEY\") | .value) |= \"$ssh_public_key\"" | \
 	yq -r "(.spec.containers[]?.env[]? | select(.name == \"SD_UID\") | .value) |= \"$owner\"" | \
 	yq -r "(.spec.containers[]?.env[]? | select(.name == \"FILE\") | .value) |= \"$FILE\"" | \
@@ -252,7 +308,7 @@ if [ -n "$pod_name" ]; then
 	yq -r -y ".metadata.labels.domain=\"$domain\"" |\
 	yq -r -y ".metadata.labels.app=\"$pod_name\"" | \
 	( [ -z "$pod_http_port" ] && cat || yq -r -y ".metadata.labels.reverseProxyPort=\"$reverse_proxy_port\"" ) |\
-	( [ -z "$nfs_storage_path" ] && cat || yq -r -y ".spec.volumes|= .+ [{\"name\":\"sciencedata\", \"persistentVolumeClaim\": {\"claimName\": \"nfs-${home_server}-${owner_str}-${nfs_storage_path}\"}}]") |\
+	( [ -z "$nfs_storage_path" ] && cat || yq -r -y ".spec.volumes|= .+ [{\"name\":\"sciencedata\", \"persistentVolumeClaim\": {\"claimName\": \"${nfs_volume_name}\"}}]") |\
 	( [ -z "$local_storage_name" ] && cat || yq -r -y ".spec.volumes|= .+ [{\"name\":\"local\", \"persistentVolumeClaim\": {\"claimName\": \"local-claim-${local_storage_name}\"}}]")
 	### SSH service
 	if [ -n "$ssh_public_key" ]; then
@@ -265,7 +321,7 @@ if [ -n "$pod_name" ]; then
 		if [ -n "$create_nfs_volume" ]; then
 			echo "---"
 			cat "$NFS_VOLUME_YAML_FILE" | \
-			sed "s|NFS_VOLUME_NAME|nfs-${home_server}-${owner_str}-${nfs_storage_path}|g" | \
+			sed "s|NFS_VOLUME_NAME|${nfs_volume_name}|g" | \
 			sed "s|STORAGE_PATH|${owner}/${nfs_storage_path}|g" | \
 			sed "s|SERVER_IP|$home_server|g"
 		fi
@@ -273,7 +329,7 @@ if [ -n "$pod_name" ]; then
 		if [ -n "$create_nfs_claim" ]; then
 			echo "---"
 			cat "$NFS_CLAIM_YAML_FILE" | \
-			sed "s|NFS_CLAIM_NAME|nfs-${home_server}-${owner_str}-${nfs_storage_path}|g"
+			sed "s|NFS_CLAIM_NAME|${nfs_volume_name}|g"
 		fi
 	fi
 	if [ -n "$local_storage_name" ]; then
@@ -291,43 +347,34 @@ if [ -n "$pod_name" ]; then
 			sed "s|LOCAL_CLAIM_NAME|local-claim-${local_storage_name}|g"
 		fi
 	fi
-	) | tee >([ -z "$dryrun" ] && kubectl apply -f - || kubectl apply --validate=true --dry-run=client -f -)
+	)
+
+  echo "$modified_yaml" >> "$logfile"
+  # Now apply the yaml and save the output of the kubectl command
+  if [[ -z "$dryrun" ]]; then
+      kubectl_output=$( kubectl apply -f - < <(echo "$modified_yaml") )
+  else
+      kubectl_output=$( kubectl apply --validate=true --dry-run=client -f - < <(echo "$modified_yaml") )
+  fi
+
+  echo "$kubectl_output" >> "$logfile"
+  # If it worked, the output should look like 'pod/jupyter... created'. In that case report success
+  regex='^pod/.*created$'
+  if [[ $kubectl_output =~ $regex ]]; then
+      echo "SUCCESS: $pod_name"
+      # begin background processes if required
+      if [[ -n "$pod_http_port" ]]; then
+          start_reverse_proxy >& /dev/null &
+      fi
+      if [[ -n "$ssh_public_key" ]]; then
+          copy_hostkeys >& /dev/null &
+      fi
+      exit 0
+  else
+      echo "FAILURE: kubectl did not create pod"
+      exit 1
+  fi
 else
 	echo "ERROR: Parsing .metadata.name from YAML failed" >&2
 	exit 2
 fi
-
-if [ -z "$dryrun" -a -n "$pod_http_port" ]; then
-	# Wait for one minute for pod to start
-	for i in {1..60}; do
-		# Find local IP
-		pod_ip=`kubectl get pod "$pod_name" -o json | jq -r '.status.podIP' | sed 's|null||'`
-		if [ -n "$pod_ip" ]; then
-			# Run Caddy reverse proxy
-			echo "INFO: Running reverse proxy caddy reverse-proxy --from https://kube.sciencedata.dk:$reverse_proxy_port --to ${pod_ip}:${pod_http_port}" >&2
-			#caddy reverse-proxy --from https://kube.sciencedata.dk:$reverse_proxy_port --to ${pod_ip}:${pod_http_port} >& /dev/null &
-			sed "s|WEBPORT|$reverse_proxy_port|" "$CADDY_FILE" > "$TMPDIR/Caddyfile-${pod_ip}-${reverse_proxy_port}"
-			sed -i "s|PODIP|$pod_ip|" "$TMPDIR/Caddyfile-${pod_ip}-${reverse_proxy_port}"
-			sed -i "s|PODPORT|$pod_http_port|" "$TMPDIR/Caddyfile-${pod_ip}-${reverse_proxy_port}"
-			export PATH=/bin/:/usr/bin:/usr/local/bin
-			caddy start -config "$TMPDIR/Caddyfile-${pod_ip}-${reverse_proxy_port}" >& /dev/null &
-			kubectl exec --stdin ${pod_name} -- cat /tmp/URI 2>/dev/null > ${TMPDIR}/uri-${pod_name}
-			break
-		fi
-		sleep 10
-	done
-	if [ -z "$pod_ip" ]; then
-		echo "ERROR: pod $pod_name did not start. NOT running reverse proxy caddy reverse-proxy --from https://kube.sciencedata.dk:$reverse_proxy_port --to ${pod_ip}:${pod_http_port}."
-    exit 1
-	else
-		# Now wait in the background for another 5 minutes for any /tmp/URI to pop up in the container
-		( for i in {1..300}; do
-			# If there's a file /tmp/URI, copy it out to /var/run/sciencedata/uri-${pod_name}
-			sleep 10
-			kubectl exec --stdin ${pod_name} -- cat /tmp/URI 2>/dev/null > ${TMPDIR}/uri-${pod_name}
-			[[ -e ${TMPDIR}/uri-${pod_name} ]] && [[ ! -s ${TMPDIR}/uri-${pod_name} ]] && rm ${TMPDIR}/uri-${pod_name}
-			[[ -s ${TMPDIR}/uri-${pod_name} ]] && break
-		done ) >& /dev/null &
-	fi
-fi
-
